#!/bin/csh
if ( $#argv != 1 ) then
	echo "motor_set on|off"
	exit 1
endif
set onoff = $1
/icc/bin/o/ccd/test/i386-linux/ccd_read_memory -interface_device pci -board utility -space y -address 0x1 > /tmp/dig_out_output.txt
set dig_out = `cat /tmp/dig_out_output.txt | grep 'Result (hexadecimal) = ' | awk ' { print $4 }'`
echo "DIG OUT  = ${dig_out}"
/home/eng/bin/inttobits ${dig_out} > /tmp/inttobits.txt 
set bit_0_set = `cat /tmp/inttobits.txt | grep -c "Bit 0 set"`
set bit_1_set = `cat /tmp/inttobits.txt | grep -c "Bit 1 set"`
set bit_2_set = `cat /tmp/inttobits.txt | grep -c "Bit 2 set"`
if( "${onoff}" == "on" ) then
	# set bit 1 motor on
	set bit_1_set = 1
else if( "${onoff}" == "off" ) then
	# set bit 1 locators off
	set bit_1_set = 0
else
	echo "Illegal in out value ${set locators_in_out}."
endif
set dig_out = 0
if ( ${bit_0_set} ) then
	@ dig_out += 1
endif
if ( ${bit_1_set} ) then
	@ dig_out += 2
endif
if ( ${bit_2_set} ) then
	@ dig_out += 4
endif
echo "New value of DIG OUT  = ${dig_out}"
/icc/bin/o/ccd/test/i386-linux/ccd_write_memory -interface_device pci -board utility -space y -address 0x1 -value ${value}
