#!/bin/sh
#
# This is a script for generating DSP code from the utilboot.asm and 
#   utilappl.asm files for the utility board
# 

DOWNLOAD=HOST

alias asm56000='wine /home/dev/sdsu/astro-cam/DSP/CLAS56/BIN/ASM56000.EXE'
#alias asm56300='wine /home/dev/sdsu/astro-cam/DSP/CLAS563/BIN/ASM56300.EXE'
alias dsplnk='wine /home/dev/sdsu/astro-cam/DSP/CLAS56/BIN/DSPLNK.EXE'
alias cldlod='wine /home/dev/sdsu/astro-cam/DSP/CLAS56/BIN/CLDLOD.EXE'

asm56000 -b -lutilboot.ls utilboot.asm
asm56000 -b -lutilappl.ls -d DOWNLOAD $DOWNLOAD utilappl.asm 
dsplnk -butil.cld -v utilboot.cln utilappl.cln
rm util.lod
cldlod util.cld > util.lod
rm utilboot.cln ; rm utilappl.cln ; rm util.cld

if [ "$DOWNLOAD" = "HOST" ] ; then
	echo ""
	echo "Created file 'util.lod' for downloading over optical fiber"
	echo ""
fi

if [ "$DOWNLOAD" = "ROM" ] ; then
	echo ""
	echo "Files named util.p0, util.p1 and util.p2 were generated"
	echo "   in Motorola S-record format for burning EEPROMs."
	echo ""
	srec -mw util.lod
fi
exit 0
