#!/bin/csh
# fake_twilight_calibration
# Create a set of strings for putting in /icc/config/twilight_calibrate_state.properties
# Any bin1 entries already present must be deleted.
set bin = 2
set now_s = `date "+%s"`
set now_ms = ${now_s}"000"
set filter_list = "SDSS-U Bessell-B SDSS-G Bessell-V SDSS-Z SDSS-I SDSS-R"
foreach filter ( ${filter_list} )
	echo "o.twilight_calibrate.last_time.${bin}.false.AlMirror.Clear.${filter} = ${now_ms}"
end
#
# $Log: not supported by cvs2svn $
#

