#!/bin/csh
# o_park_filter_wheel cron job
# Moves the filter wheel to a set position
# $Header: /space/home/eng/cjm/cvs/ioo/scripts/o_park_filter_wheel,v 1.2 2012-07-25 16:11:52 cjm Exp $
set hostname = "o1"
set port = 7979
set park_filter = "SDSS-U"
set bin = 2
set year = `/bin/date +"%Y"`
set doy = `/bin/date +"%j"`
set log_filename = "/icc/log/o_park_filter_wheel_${year}_${doy}.txt"
/bin/date  >>& ${log_filename}
(java ngat.o.test.SendConfigCommand -address ${hostname} -port ${port} -filter ${park_filter} -xBin ${bin} -yBin ${bin} >> ${log_filename} ) >>& ${log_filename}
set config_status = $status
if ( ${config_status} != 0 ) then
	echo "An error occured: ${config_status}." >> ${log_filename}
	exit 1
endif
#
# $Log: not supported by cvs2svn $
# Revision 1.1  2012/07/25 10:49:27  cjm
# Initial revision
#
#
